only_rules:
  - closure_parameter_position
  - colon
  - comma
  - comment_spacing
  - computed_accessors_order
  - discouraged_direct_init
  - duplicate_imports
  - generic_type_name
  - identifier_name
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_random
  - mark
  - no_space_in_method_call
  - opening_brace
  - protocol_property_accessors_order
  - redundant_objc_attribute
  - redundant_string_enum_value
  - return_arrow_whitespace
  - statement_position
  - type_name
  - vertical_parameter_alignment
  - custom_rules

closure_parameter_position:
  severity: error

colon:
  severity: error

comma:
  severity: error

comment_spacing:
  severity: error

computed_accessors_order:
  severity: error

discouraged_direct_init:
  severity: error

duplicate_imports:
  severity: error

leading_whitespace:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

legacy_random:
  severity: error

mark:
  severity: error

no_space_in_method_call:
  severity: error

opening_brace:
  severity: error

protocol_property_accessors_order:
  severity: error

redundant_objc_attribute:
  severity: error

redundant_string_enum_value:
  severity: error

return_arrow_whitespace:
  severity: error

statement_position:
  severity: error

vertical_parameter_alignment:
  severity: error

implicit_return:
  severity: error

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 1000
    error: 1000


# Custom Rules
custom_rules:
  no_print:
    name: "No Print"
    regex: "print\\("
    message: "There should be no print statements left in the Swift file."
    severity: error

  no_blank_lines_under_the_opening_brace:
    name: "No blank lines under the opening brace"
    regex: '(?-s)^\s{4,}.*(func|var|let|\))\s.*\{\n\s*\n'
    message: "There must be no blank lines under the opening brace."
    severity: error
  
  no_blank_lines_above_the_closing_brace:
    name: "No blank lines above the closing brace"
    regex: '\n\s*\n\s*\}'
    message: "There must be no blank lines above the closing brace."
    severity: error
  
  no_too_many_blank_lines:
    name: "No too many blank lines"
    regex: '(?-s)^.+\n(?:\s*\n){2,}\s*\w+(?!// MARK: -)'
    message: "There are too many blank lines"
    severity: error
  
  no_get_property:
    name: "No Get Property"
    regex: '(let|var)\s+get.*'
    message: "Property name must not start with 'get'."
    severity: error
  
  no_get_method:
    name: "No Get Method"
    regex: 'func\s+get.*'
    message: "Method name must not start with 'get'."
    severity: error
  
  input_line_break_under_extension:
    name: "Input line break under extension"
    regex: '(?-s)extension\s.*\{\n.*[^\s]+'
    message: "Extension must be followed by a single line."
    severity: error
  
  input_line_break_under_class_struct_enum_protocol:
    name: "Input line break under class, struct, enum, protocol"
    regex: '(?-s)(class|struct|enum|protocol)\s(?!func|var).*\{\n.*[^\s]+'
    message: "Class, Struct, Enum, Protocol must be followed by a single line."
    severity: error
  
